site_name: Zebrunner
repo_url: https://github.com/zebrunner/zebrunner
repo_name: Zebrunner

# Page tree
nav:
  - Overview: index.md
  - Getting started:
    - Part 1: getting_started.md
    - Part 2: getting_started.md
  - User guide:
    - User profile: guide/user_profile.md
    - Dashboards: guide/dashboards.md
    - Widgets: guide/widgets.md
    - Projects: guide/projects.md
    - Test runs and sessions: guide/test_runs_and_sessions.md
    - User management: guide/user_management.md
    - Integrations: guide/ntegrations.md`
theme:
  name: 'material'
  favicon: assets/images/favicon.png
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'green'
